const branchTypes = {
    FETCH_BRANCHES_START: 'FETCH_BRANCHES_START',
    FETCH_BRANCHES_SUCCESS: 'FETCH_BRANCHES_SUCCESS',
    FETCH_BRANCHES_FAILURE: 'FETCH_BRANCHES_FAILURE',
    SET_BRANCH: 'SET_BRANCH',
};

export default branchTypes;
